name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "*/3 * * * *" # Run every 3 minutes

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://next-onlyoffice-git-main-dholakiyakinjals-projects.vercel.app"
          cmd_options: "-a -w report_html.html"

      - name: Debug - List all files
        run: ls -R .

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: report_html
          path: report_html.html
