name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * *" # daily scan at 3 AM

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://next-onlyoffice-git-main-dholakiyakinjals-projects.vercel.app"
          cmd_options: "-a"

      - name: Debug - List all files
        run: ls -R .

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: report_html
          path: |
            report_html.html
            report_md.md
            report_json.json
