name: OWASP ZAP + SBOM + Vulnerability Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * *"

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      # DAST(ZAP)
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://next-onlyoffice-git-main-dholakiyakinjals-projects.vercel.app"
          cmd_options: "-a -w report_html.html"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: DAST (ZAP)
          path: report_html.html

      # SBOM
      - name: Generate SBOM
        uses: anchore/sbom-action@v0.14.3
        with:
          format: cyclonedx-json
          output-file: sbom.json
          upload-artifact: false

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: sbom.json

      # Trivy (Container immage and package scanning)
      - name: Vulnerability Scan with Trivy (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-fs-results.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"
          exit-code: "0" # Don't fail the build

      - name: Vulnerability Scan with Trivy (Dependencies)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "json"
          output: "trivy-deps-results.json"
          severity: "CRITICAL,HIGH,MEDIUM"
          exit-code: "0" # Don't fail the build

      - name: Upload Trivy SARIF Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Vulnerability Scan (SARIF)
          path: trivy-fs-results.sarif
          if-no-files-found: warn

      - name: Upload Trivy JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: Vulnerability Scan (JSON)
          path: trivy-deps-results.json

      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-fs-results.sarif
          category: "trivy-fs"
        continue-on-error: true

      # SemGrep (Code Vulnerability)
      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run Semgrep Scan
        id: semgrep
        continue-on-error: true
        run: |
          semgrep --config=p/security-audit \
                  --config=p/owasp-top-ten \
                  --config=p/javascript \
                  --sarif \
                  --output=semgrep-results.sarif \
                  --error \
                  --disable-version-check \
                  --no-git-ignore \
                  --metrics=off \
                  . || true

      - name: Upload Semgrep SARIF Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-sarif-report
          path: semgrep-results.sarif
          if-no-files-found: warn

      - name: Upload Semgrep SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: semgrep-results.sarif
          category: "semgrep"
        continue-on-error: true
