name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * *" # daily scan at 3 AM

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://next-onlyoffice-git-main-dholakiyakinjals-projects.vercel.app"
          cmd_options: "-a -w report_html.html"

      - name: Debug - List all files
        run: ls -R .

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: report_html.html

      - name: Generate SBOM
        uses: anchore/sbom-action@v0.14.3
        with:
          format: cyclonedx-json
          output-file: sbom.json
          upload-artifact: false

      - name: Upload SBOM Report
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
